Made the README more readable
rafaelmardojai/blanket pull request #272
Opened 2022-08-31 15:09 UTC by Its-Juice

I just wanted to read it at night without taking my eyes out

2022-08-31 15:11 UTC, Its-Juice commented
Oh also i want to translate blanket to greek

2022-09-01 12:50 UTC, rafaelmardojai commented
Thanks!

2022-09-01 12:56 UTC, rafaelmardojai requested changes

2022-09-01 12:56 UTC, rafaelmardojai commented on blanket/main.py
> +gi.require_version('Gtk', '3.0')
> There's no reason to require gtk 4. It works perfectly with gtk3

This app requieres GTK 4, starting because we use libadwaita that is GTK4 only.

 Please, revert that change so I can merge the rest.

2022-09-01 16:08 UTC, Its-Juice commented
> Thanks!
btw i am done with the translation

2022-09-01 17:15 UTC, merged